project:
  type: website

website:
  title: "matt roumaya"
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - text: "blog"
        file: index.qmd
      - projects.qmd
      - icon: github
        href: https://github.com/mattroumaya
      - icon: linkedin
        href: https://www.linkedin.com/in/mattroumaya
      - icon: mastodon
        href: https://techhub.social/@mattroumaya

format:
  html:
    css: styles.css
    toc: true
    metadata:
      pagetitle: "matt roumaya"
  

editor: visual




